version: "3.8"
services:
  db:
    container_name: onedata
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: byteone
    ports:
      - "5432:5432"
    volumes:
      - postgre:/var/lib/postgresql
    networks:
      - one

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  onebyte:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - DATABASE_URL="postgresql://root:root@onedata:5432/sample"
    ports:
      - "4000:4000"
    networks:
      - one
volumes:
  postgre:

networks:
  one:
    driver: bridge
